name: Build CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
    windows:
        runs-on: windows-latest
        steps:
        - name: Download code
          uses: actions/checkout@v3
        
        - name: Install UPX
          uses: crazy-max/ghaction-upx@v2
          with:
            install-only: true

        - name: Patch script with webhook URL
          run: python3 .github/workflows/webhook_patcher.py __main__.py hawkeye_placeholder_webhook ${{ secrets.HAWKEYE_WEBHOOK_URL }}

        - name: Install MSVC
          uses: TheMrMilchmann/setup-msvc-dev@v2
          with:
            arch: x64
            uwp: false
            spectre: true

        - name: Build bootloader and script
          run: |
            git clone --single-branch --depth=1 https://github.com/pyinstaller/pyinstaller.git
            cd pyinstaller
            cd bootloader
            python3 ./waf all
            cd ..
            python3 setup.py install
            cd ..
            python3 -m pip install -r requirements.txt
            pyinstaller -F __main__.py
            move dist/__main__.exe hawkeye.exe
        
        - name: Upload as artifact
          uses: actions/upload-artifact@v3
          with:
            name: build
            path: hawkeye.exe
        
        - name: Release website
          run: python3 .github/workflows/website_release.py hawkeye.exe __main__.py jjno232/TierlistHawkeye main
        
        - name: Push changes
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: "Release website"
            file_pattern: "index.md"
            skip_dirty_check: true
