name: Release CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
    windows:
        runs-on: windows-latest
        steps:
        - name: Download code
          uses: actions/checkout@v3
        
        - name: Install UPX
          uses: crazy-max/ghaction-upx@v2
          with:
            install-only: true

        - name: Patch script with webhook URL
          run: python3 .github/workflows/webhook_patcher.py __main__.py hawkeye_placeholder_webhook ${{ secrets.HAWKEYE_WEBHOOK_URL }}

        - name: Build tool
          run: |
            python3 -m pip install pyinstaller
            python3 -m pip install -r requirements.txt
            pyinstaller -F __main__.py
            move dist/__main__.exe hawkeye.exe
        
        - name: Write release body
          run: python3 .github/workflows/release_body.py
        
        - uses: ncipollo/release-action@v1
          with:
            artifacts: "hawkeye.exe"
            bodyFile: "body.md"
