name: Release Build CI

on:
  workflow_dispatch:

jobs:
    windows:
        runs-on: windows-latest
        steps:
        - name: Download code
          uses: actions/checkout@v3
        
        - name: Install UPX
          uses: crazy-max/ghaction-upx@v2
          with:
            install-only: true

        - name: Patch script with webhook URL
          run: python3 .github/workflows/webhook_patcher.py __main__.py hawkeye_placeholder_webhook ${{ secrets.HAWKEYE_WEBHOOK_URL }}

        - name: Build tool
          run: |
            python3 -m pip install pyinstaller
            python3 -m pip install -r requirements.txt
            pyinstaller -F __main__.py
            move dist/__main__.exe hawkeye.exe
        
        - name: Upload as artifact
          uses: actions/upload-artifact@v3
          with:
            name: build
            path: hawkeye.exe
        
        - name: Release website
          run: |
            python3 .github/workflows/website_release.py hawkeye.exe __main__.py jjno232/TierlistHawkeye main
            git config --local user.name  ${{ github.actor }}
            git config --local user.email "${{ github.actor }}@users.noreply.github.com"
            git add ./index.md
            git commit -m "Release website"
        
        - name: Push changes  # push the output folder to your repo
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            force: true
